"""Add Game.ckan_enabled

Revision ID: f7d352d49c2b
Revises: 73c9d707134b
Create Date: 2020-10-16 22:18:26.490542

"""

# revision identifiers, used by Alembic.
revision = 'f7d352d49c2b'
down_revision = '73c9d707134b'

from alembic import op
from sqlalchemy import Boolean, Column, Integer, orm
from sqlalchemy.ext.declarative import declarative_base
import sqlalchemy as sa

Base = declarative_base()


class Game(Base):  # type: ignore
    __tablename__ = 'game'
    id = Column(Integer, primary_key=True)
    ckan_enabled = Column(Boolean, default=False, index=True)


def upgrade() -> None:
    # autogenerated
    op.add_column('game', sa.Column('ckan_enabled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_game_ckan_enabled'), 'game', ['ckan_enabled'], unique=False)
    # end

    bind = op.get_bind()
    session = orm.Session(bind=bind)

    ksp = session.query(Game).get(3102)
    if ksp:
        ksp.ckan_enabled = True

    session.commit()


def downgrade() -> None:
    # autogenerated
    op.drop_index(op.f('ix_game_ckan_enabled'), table_name='game')
    op.drop_column('game', 'ckan_enabled')
    # end
