"""add ML/AI field for mods

Revision ID: 4621f654f05a
Revises: fb2881831917
Create Date: 2026-10-04 10:23:18.909482

"""

# revision identifiers, used by Alembic.
revision = '4621f654f05a'
down_revision = 'fb2881831917'

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featured_priority'), table_name='featured')
    op.create_index(op.f('ix_featured_priority'), 'featured', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_featured_priority'), table_name='featured')
    op.create_index(op.f('ix_featured_priority'), 'featured', [sa.literal_column('priority DESC')], unique=False)
    # ### end Alembic commands ###
